[package]
name = "spacerocks"
version = "0.1.0"
edition = "2021"
authors = "Kevin Napier"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32.2"